### ISSUE TITLE
Network home - panel 2 text refinements

### ISSUE THREAD

**Issue by tomtheall** [ventuso/Fi-Test#102]
a minor enhancement. Match text information on the 2nd panel closer to the comp. Image reference attached.
- Left align
- change text color to #666666
- decrease size of text

 
![edits-35](https://cloud.githubusercontent.com/assets/11476339/7286830/8959679a-e914-11e4-994f-63033ee6394e.jpg)

**Comment by nhanventuso** [comment]
I fixed on iOS version 1.0.46
