### ISSUE TITLE
Android & iOS Initialization pages need to say Be Free instead of Free the Internet

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#11]
Android and iOS - 
On the very first screen that is displayed after launching Fi and under the Fi logo the words Free the Internet appear.  

This needs changed to Be Free.

Needs changed before March 25th as we want our brand to be consistent.  

![init_page_wording_change](https://cloud.githubusercontent.com/assets/8836291/6660405/38e44468-cb66-11e4-8d8b-444166add1ee.png)

**Comment by nhanventuso** [comment]
BE FREE
