### ISSUE TITLE
Android: Map location defaults to the African continent - Should be North America

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#12]
When I open Fi for the first time the map default location is set to Africa.  This should be changed to North America.  

![note2_hw_sw_version_taren](https://cloud.githubusercontent.com/assets/8836291/6660423/a98a5928-cb66-11e4-872c-959e56cd01c6.png)

**Comment by jweid** [comment]
this seems to be working fine on iPhone 5s

**Comment by dangtran89** [comment]
fixed in 1.0.7
