### ISSUE TITLE
Android & iOS:  Replace Sparks with Apps

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#13]
Change Sparks to Apps.   

![sparks_change](https://cloud.githubusercontent.com/assets/8836291/6660861/2cd5bfd0-cb70-11e4-966f-e34981f5049b.png)

**Comment by baonguyenventuso** [comment]
@TarenJP 
In here, follow the new instruction we will apply change as follow
Sparks ==> Apps 
Deals ==> Bonus 
Files ==> Media 

It will available in next test release.

Best regards,

**Comment by TarenJP** [comment]
Please make this change prior to the demon on 3/25/15.

**Comment by dangtran89** [comment]
fixed in version 1.0.7
