### ISSUE TITLE
Sparks folder (now Apps folder) tappable areas are off center or too small (Samsung Note 2)

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#19]
When I tap on any of the Apps in the folder below I must tap to the very top of the square icon in order for Fi to interpret my tap.  Can you make the tappable area larger or centered more?  

Not sure if this is just my device or if this affects other Androids. 

![tap_area_off_center](https://cloud.githubusercontent.com/assets/8836291/6661250/53b96c30-cb77-11e4-92d8-d321c4679d21.png)

**Comment by jweid** [comment]
this seems to be working properly on iPhone 5s I have clicked all over the different boxes and it seems to be working as desired

**Comment by TarenJP** [comment]
I meant to update this.   It was because I used a system setting to
increase the font size.

**Comment by dangtran89** [comment]
fixed in version 1.0.7
