### ISSUE TITLE
Guest Book messages not being polled or sent from Android - (Samsung Note 2)

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#20]
A few problems in the Guest Book area that probably weren't clear because I failed to document the specifics on how we want this Chat/Messaging feature to work.  

1)  Guest Book needs renamed to Message Board in the Android and iOS apps
2)  Fi users should be able to:

     a) Enter and send a text only message that is visible to everyone actually connected on that wifi network (messages/chat are associated with the MAC address of that merchant).   Also, it would probably be a good idea to generate a UUID for each merchant rather than rely on the MAC address for our main key into this merchant table.  The mac's will change over time.  Not sure how that's being handled, but wanted to make the suggestion.  

     b) Tap the universal Photo Icon - and this should launch their camera to take a picture.  (don't want them to select from their own Gallery as someone could accidentally upload a photo they didn't want - and then it would have to be deleted  - probably by us.

     c) View other's comments/photos.  Photos should appear as scaled down thumbnails and go full screen if they tap on the image.  Saving the image and screenshots should be disabled.

**Comment by baonguyenventuso** [comment]
@TarenJP 

This issue is all about our web-socket, it is fixed in the current version I have here and will release to you soon. 

As in our new instruction, Guest Book will change to MessageNow.

For your suggestion on (2): (a) and (c) are available, for (b), let put it in next phase. 

Best regards,
T. Bao

**Comment by nhanventuso** [comment]
fixed on ios.
