### ISSUE TITLE
Default GPS location should be the last known location after a user exits the app and then relaunches

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#22]
In order to conserve battery and make an overall better user experience - the last known GPS fix should be used in the Fi clients (iOS and Android) so we don't use the high-level default location as the user's starting point.  

Ideal solution would be:  Use last known GPS location (example:  Dallas) then if their location has changed by a large amount - then have Google Maps pan and zoom to the new location.

**Comment by baonguyenventuso** [comment]
@TarenJP  

Thanks for great suggestion, we will apply this soon.

**Comment by nhanventuso** [comment]
applied.
