### ISSUE TITLE
Happening Now (HereNow) updates initiated from the web portal should be annotated "By Admin"

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#24]
Android and iOS enhancement

The happening now feed (being renamed to HereNow) is a multi-purpose feed.  It is to be used to display the following content only:

1) Text/images/videos from the network admin initiated from the HereNow web portal.  
2) Static Ads (WiFi triggered ad) should appear here if the folder is open when the person first connects. 
3) BlueTooth beacon triggered ads should also appear here after we integrate Bluetooth into Fi (future release)

**Comment by tomtheall** [comment]
Taren, I imagined user chat messages from the chat app will appear in this home-page feed as well?

Essentially it is all relevant network activity (user messages and new deals/uploads/messages from admin)

Down the line…. if a network has a relevant app installed, those apps should display certain activity to this home-page feed as well. (Examples…a jukebox app displaying a currently playing song, or a football stadium's "scoreboard" app displaying an updated score card upon touchdown.)

**Comment by TarenJP** [comment]
Tom - We can take this approach for now.  But I want the HereNow to be mostly reserved for Wireless Beacon display.  This is what you open for the HereNow Experience.   But we can make that shift after BlueTooth is integrated in release 2.0.  Taking your suggested approach will get people used to looking in the HereNow folder for real time updates.

**Comment by baonguyenventuso** [comment]
@TarenJP  & @tomtheall 

Happenning Now (HereNow) is currently display activities of network's admin and users who is connecting to that network, including:

Admin:
- Post image 
- Post deal 
- Post file 
- All above with comments/subject and user can download or claim the items 

User:
- Post chat in MessageNow (Chat/ Guest Book) 

I will ask the team to continue implement by making the [Download]/[Save] button work and implement the Wifi Trigger (Static Ad Delivery) work in here. Notice that, each merchant currently have only 1 Wifi Trigger Ad (can be more in the future), if there are update, it will be added as new one. 

As this tag is an enhancement, I will let the team stay focus on issues/bugs and put this as low priority to solve. 

Best regards & have a nice day,

**Comment by baonguyenventuso** [comment]
Fixed on Android and iOS latest release. 

Best regards,
