### ISSUE TITLE
Fi Service Request minor changes

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#26]
1) Change to this:
By making a service request in this area, you are helping enable the world's first free mobile data network.  

2) After a user requests service - a gray "system pop up" should appear briefly and say, "You're awesome!  Don't forget, you can also share your personal network with friends and family to easily access even more Free Mobile Data."

**Comment by tomtheall** [comment]
I also added 2 edits to this service request page….see issue #31

- - Should I put those edits as comments within this issue? (#26-3, #26-4, etc.)

**Comment by TarenJP** [comment]
Tom-  I'll let you decide what we say in these messages.  I recall you saw where simply saying please and thank you in your app that people will rate you higher.  So please use that as the reference point for these messages.  I want people to know we really appreciate it when they make a service request.  That's what the Fi Pro badge will be for in future releases.

**Comment by baonguyenventuso** [comment]
@TarenJP @tomtheall 

I answered Tom on issue #31 , for this request, I will apply the change in the release. 

Thanks & best regards,

**Comment by nhanventuso** [comment]
I fixed on version 1.0.20
