### ISSUE TITLE
Tapping Refresh button causing Fi icons to disappear and other unexpected behavior

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#28]
Had a good GPS fix this morning.  Fi defaulted map view to North America.  

While at the North America level - I tapped the refresh button at the lower left hand side of the map.  
Fi zoomed to my current location, icons appeared then disappeared without my interaction. 

Other unexpected behavior observed:  While on the same screen, I tapped the refresh button.  The icons would appear for 3 seconds, then disappear.  If I tapped the refresh button, the same result and timing each time - 3 seconds and the icons disappear.

**Comment by vothanhkiet** [comment]
Please provide us device's name and software version.

**Comment by TarenJP** [comment]
Attached....

**Comment by TarenJP** [comment]
I don't know if the previous attachment was included as I replied via email.  Here's the HW/SW version of the device I tested with.  

![note2_hw_sw_version_taren](https://cloud.githubusercontent.com/assets/8836291/6681420/4304cfe8-cc34-11e4-9cc3-99cbe325a711.png)

**Comment by jweid** [comment]
I've tried to reproduce this on the iPhone 5s without any luck... at every start and after reboot it always shows on the map exactly where I am
