### ISSUE TITLE
My user profile is not shown as a HereNow User - after manually connecting to a BSSID

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#30]
Title says it all.  Here's the evidence - notice Fi notification in tray indicating I successfully connected to the network and Fi knew about it.  I'm thinking my user either didn't get dropped in that DB (list) or my client didn't poll that directory.  

![user_not_connected](https://cloud.githubusercontent.com/assets/8836291/6672292/7f347014-cbd9-11e4-937f-7f51b73b8fbf.png)

**Comment by jweid** [comment]
on iOS Iphone 5s I am seeing the same thing now... all I see is Ken logged in on Fi app when we know that myself and Troy are currently on as well 

Ken confirmed the issue

**Comment by baonguyenventuso** [comment]
Dear @TarenJP and @jweid ,

This issue is now fixed. You will see in the next release. 

Best regards,
