### ISSUE TITLE
Disconnected from current WiFi network but failed to connect to "Colvista Country Club" 

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#32]
Setup:

Samsung S3 (HW/SW version below)
No 4G service - only WiFi
Connected to a separate working WiFi connection (personal hotspot) with VPN to FoxFi (with stored credentials).  

After successfully logging into Fi from this device for the first time - I tapped the Connect button on the Colovista Country Club home page.  

Fi appeared to disconnect me and possibly made an attempt to auto-negotiate the password exchange, as I received an "incorrect password" notification from the Android OS (WiFi event).  

I have no other trace information to support debug at this time.  

![s3_hw_sw_version](https://cloud.githubusercontent.com/assets/8836291/6673015/1624ba20-cbde-11e4-8edf-e421f695d2a0.png)

**Comment by baonguyenventuso** [comment]
@TarenJP 

We fixed in our next release, please help us to recheck this case and re-open the issue if it happen again. 

Thanks & regards,
