### ISSUE TITLE
HereNow Feed:  Content push had the text of different photo

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#33]
This was supposed to say, "Who's going to tell these guys this isn't how you play skins?"  

It got the text from a content push of a sunset.  The Sunset picture did not have text transposed.  

![content_swap_on_a_freebie_feed_push](https://cloud.githubusercontent.com/assets/8836291/6675040/f474f170-cbeb-11e4-95d1-4287b94515b9.png)

**Comment by dangtran89** [comment]
fix in 1.0.7
