### ISSUE TITLE
Apps Menu cosmetic change

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#35]
Occurred on Samsung S3 (SCH-I535) Hardware Version:  I535.10
Android 4.1.2

See snapshot for fix:
![appsmenu_cosmetic](https://cloud.githubusercontent.com/assets/8836291/6681572/bcafc56c-cc36-11e4-9ba7-0a3c2072e745.png)

**Comment by jweid** [comment]
his is working properly on iOS Iphone 5s

**Comment by dangtran89** [comment]
fixed in version 1.0.7

**Comment by dangtran89** [comment]
fixed in 1.0.7
