### ISSUE TITLE
iOS "In X user network" doesn't increase immediately after successful following 

### ISSUE THREAD

**Issue by baonguyenventuso** [ventuso/Fi-Test#38]
After I am following a merchant  successfully, this number still stay the same.

**Comment by tomtheall** [comment]
I noticed this also, number updates after quitting and restarting app.

ALSO - the color of this sentence seems too dark….color should be #999999 (light grey) so that it is readable on top of all background images.

**Comment by nhanventuso** [comment]
fixed light grey on 1.0.20
