### ISSUE TITLE
Clicking on photo adds photo to gallery

### ISSUE THREAD

**Issue by jweid** [ventuso/Fi-Test#42]
When I click on the photo thinking it would expand it I do get a photo saved msg but thinking double click would make it bigger I ended up with 8 saved photos in my gallery. 

Probably want to have a do you want to save to gallery validation since most people think clicking on something will make it larger.

**Comment by vothanhkiet** [comment]
This is an enhancement for mobile right ?

**Comment by baonguyenventuso** [comment]
Hi @jweid ,

I think you reported on Mobile, I will add tags and put this implement soon in the releases. 

Thanks & Best Regards,

**Comment by tomtheall** [comment]
Tapping a photo should enlarge the photo to full screen with black background. Then option swipe left/right to next photos or to download/save to phone by pressing a download icon.

I can mock this up later this week if needed.

(Commenting on photos may be good enhancement later but until it can be mapped out, let's disable photo commenting for now and study best usages.)

**Comment by nhanventuso** [comment]
iOS version 1.0.48 have really applied, please test again.
