### ISSUE TITLE
Highlight a user In Users doesn't do anything till you click < 

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#43]
Testing on Iphone 5.
Software version 8.2
FI version 1.0.10
Connected to Range within FI
Did view network.  Then clicked on the black star.
Clicked on  Users icon
Showed ken as a user.  
I highlighted Ken.  Nothing happened.
Clicked the < to go back.
Thats when it looks like maybe Kens info came up.
See attachment below.
![img_0146](https://cloud.githubusercontent.com/assets/11478454/6700844/3f478996-cce2-11e4-8f88-80ba6a742eb7.PNG)

**Comment by nhanventuso** [comment]
fix at next version 1.0.20
