### ISSUE TITLE
Add new Merchant page doesn't function properly on IE11

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#44]
Trying to use Internet Exploder 11 to add a new merchant in.
Google map at bottom doesn't show up
Type in address at bottom  and then click search and nothing happens.

**Comment by hovanphuong** [comment]
Do not see this bug. Please re-check again. Thanks.
![screenshot from 2015-03-18 16 17 46](https://cloud.githubusercontent.com/assets/9562974/6705788/bea9289a-cd8a-11e4-828f-2ce7c477c5e9.png)
