### ISSUE TITLE
Black X button covers bottom middle icon

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#45]
Testing on Iphone 5.
Software version 8.2
FI version 1.0.10
Connected to Range within FI
Click on view network
Click on Black *
All the different icon squares are shown.
If you scroll all the way down. The bottom app icon in the middle is always covered by the black x button
See picture below.
![img_0147](https://cloud.githubusercontent.com/assets/11478454/6701950/b69469ce-ccf1-11e4-90f6-9e9baef45ca3.PNG)

**Comment by baonguyenventuso** [comment]
Fixed on next release
