### ISSUE TITLE
addlook in update merchant takes you back to main merchant page

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#48]
If you click on update merchant on the merchant web page.  Then click on addlook.  It just takes you back to the merchant main page.

**Comment by baonguyenventuso** [comment]
Dear troywa,
I checked this issue, the merchant update to add look worked well. Please try again, if it still happen, please let me know your browser, is it Safary or IE ? 

Best regards,

**Comment by baonguyenventuso** [comment]
Fixed on next release of Portal. If it happen again, please let us know your browser and its version
