### ISSUE TITLE
Add docbox doesn't seem to do anything.

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#49]
On merchant web page.
Did update merchant.
Clicked on ADDDOCBOX
Filled out all fields including file/picture
Selected activate
Then clicked on submit
Seemed to take it ok
Went back to merchant page.
Clicked on view docbox list paperclip icon.
Nothing shows up.
Can't seem to find the docbox I added anywhere.

**Comment by TarenJP** [comment]
Check the Happening Now feed.   This is why I went through the product
element naming exercise yesterday.   We needed to match portal to client
folders.

**Comment by troywa** [comment]
But I can't even see what I added on the merchant web page for docboxes

**Comment by baonguyenventuso** [comment]
Hi Troywa and Taren,

Please check back this case. I has just checked, it worked well. The case happened on Troywa test may come from our server side updating. Let me know if you still get that issue. I will let this issue still Open. 

Regards, 

PS: This restrict only .pdf file for the moment
