### ISSUE TITLE
iOS - On list page, blue rings should be white

### ISSUE THREAD

**Issue by tomtheall** [ventuso/Fi-Test#52]
iOS 1.0.15
On list page, blue rings should be white.

QUESTION:
Also, won't this page eventually only show nearby networks? It is currently showing all networks in Dallas…this will become a problem when there are thousands of Fi Networks.

**Comment by baonguyenventuso** [comment]
@tomtheall 
The load area on the map is pretty large for now and same to display on the map, if you agree on, we can limit the area of display and also limit on the list up to 20 items. Thanks

**Comment by TarenJP** [comment]
Let's keep the load area large for the beta.  As we begin scaling the
number of networks,  we may need to come up with a clustered icon that
displays the number of networks,  then tapping that icon zooms to those X
number of networks.   So a city level view might show "9,000" and a zoom to
a street level would break out the individual icons we use today.

But for this release lets keep the load area large.


  My 2 cents..

Taren

**Comment by nhanventuso** [comment]
I fixed "On list page, blue rings should be white."
