### ISSUE TITLE
Android crashes when zoom to Dallas area.

### ISSUE THREAD

**Issue by kenle99** [ventuso/Fi-Test#53]
Opened Fi
Map defaulted to North America,  as expected.
Zoomed to Dallas area.
The map Screen never focused.
Fi exited

See attached crash file
![fitest txt](https://cloud.githubusercontent.com/assets/8815191/6767690/166ce29a-d00d-11e4-80dc-8ff110273514.png)

**Comment by kenle99** [comment]
I will send in email as txt file is not supported.

**Comment by baonguyenventuso** [comment]
We detected that issue here, some time it happened in Vietnam as well. It will be fixed soon.
