### ISSUE TITLE
Not supported in this region Alert needs reworded

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#57]
Testing on Iphone 5c.
Software version 8.2
FI version 1.0.29
Connected to Range within FI
The following alert needs re-worded.
![img_0154](https://cloud.githubusercontent.com/assets/11478454/6910155/c6e7a32c-d714-11e4-91e9-2647f2321b86.PNG)

**Comment by tomtheall** [comment]
Typically when you tell a user something bad, it helps to let them know that their voice is heard, then give them a task to do to help them achieve the task. If we aren't allowing them to request service, how else can the user be helpful? Share with a friend? Share on Facebook? Go to a blog post and get educated? etc.

Question: Is this just for when making service requests? If so, what is the reason for not allowing requests outside of Dallas?

For now, let's just fix the grammar and go with: "Fi is not currently available in this region. Hang tight, the revolution is coming."

**Comment by kenle99** [comment]
Let's remove the limitation all together.  If we need to restrict in the future, then it is easy to put back the restriction.

**Comment by nhanventuso** [comment]
fixed on 1.0.32
