### ISSUE TITLE
Networks out of range displaying as in range (blue)

### ISSUE THREAD

**Issue by tomtheall** [ventuso/Fi-Test#58]
iOS 8.1.2 (12B440)
iPhone 6
Fi ver 1.0.29

Not sure exactly when or how it does it, I can recreate it by zooming in near the networks, hitting refresh, and black networks turn into blue networks. (screenshots attached)

![img_4556](https://cloud.githubusercontent.com/assets/11476339/6992693/d7c8acb6-da9f-11e4-9fb8-a0e4198734db.PNG)
![img_4553](https://cloud.githubusercontent.com/assets/11476339/6992694/d7fb3c4e-da9f-11e4-9ccc-d8660ee6fa39.PNG)

**Comment by nhanventuso** [comment]
It is good on iOS version 1.0.48, please help me to test again, thank you!
