### ISSUE TITLE
Entering password in initial sign up screen

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#6]
Testing on Iphone 5.
Software version 8.1.3
FI version 1.0.10

In the create account window where you are to enter your email address and password and optional mobile number to sign up.

There is a "show password" option that you can click on at the bottom of the page just above the "Sign Up" botton. If you don't click on "show password" right then and you click in the email address or password box the keyboard pops up and you don't see the "show password" option anymore.  So when you're typing your password you cant see it.  So if you fat finger your password and hit "Sign Up" the user could have entered an incorrect password and they wouldn't know it.

I think 1 or 2 things should be corrected on this page.

1.  Either move the "show password" option to right above or below the password box.  So the pop up keyboard doesn't hide it.
2.  Add another password confirmation box so the user has to enter the same password twice so they know its correct.
3.  Don't even hide the password as the type it in the Sign Up screen.  That way the always see it before they hit "Sign Up"

**Comment by baonguyenventuso** [comment]
@troywa 
I will try to move the Show Password option a bit (in your suggest 1) so user can hit it even if the keyboard pop-up. I don't think 2 and 3 should be implement, 3 can result a lost password seeing by other people, 2 seem not a logic on mobile, seem it is annoy user to re-type password, if we do this way, we won't need to have "show password" anymore. For reference, see the way on Wifi Password entering on iOS and Android. 

Regards,

**Comment by nhanventuso** [comment]
apply move "show password"
