### ISSUE TITLE
iOS - map view, make style of map buttons consistent with list view buttons.

### ISSUE THREAD

**Issue by tomtheall** [ventuso/Fi-Test#62]
(See attachment and explanation below.)

For consistency, let's make the "connect" and "follow" buttons be the rounded buttons instead of full view. It shows more of the map and feels more tappable.

- Also, if possible, add motion animation when switching between build and a selected network.

![edits-05](https://cloud.githubusercontent.com/assets/11476339/6993986/963838d8-dacd-11e4-8ef4-da9656817e36.jpg)

**Comment by nhanventuso** [comment]
iOS fixed on version 1.0.37
