### ISSUE TITLE
Network Home Pages - Turn on "paging" for info slider cards.

### ISSUE THREAD

**Issue by tomtheall** [ventuso/Fi-Test#68]
On iOS, this area is scrolling instead paging. Needs to snap to one page or the other.
See attachment:

![edits-15](https://cloud.githubusercontent.com/assets/11476339/6994056/269955cc-dad0-11e4-9a29-09c9bc103d41.jpg)

**Comment by nhanventuso** [comment]
fixed on iOS version 1.0.37
