### ISSUE TITLE
New "Freebie" content not displayed in Files folder 

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#7]
I configured new merchant:  Colovista Country Club.  Then I added a Freebie, which is supposed to appear in the "Files" folder in the Blue Sparks menu.  It looked like the Fi client tried to fetch the image, but failed to render it.   

App screenshot:
![screenshot_2015-03-14-20-35-12](https://cloud.githubusercontent.com/assets/8836291/6654330/646ee502-ca8a-11e4-91f0-398904e37997.png)

Device HW and SW Versions

![note2_hw_sw_version_taren](https://cloud.githubusercontent.com/assets/8836291/6654341/57ac5d80-ca8b-11e4-90d8-3317b9b579ea.png)

**Comment by TarenJP** [comment]
Since opening this, I found that when a Freebie is configured for a Merchant, that this content is pushed into the feed.  This is working the way we intended it to.  

To close this issue, you can simply rename the Freebie in the Web portal to "Post to Chat Feed".

**Comment by dangtran89** [comment]
fixed in version 1.0.7
