### ISSUE TITLE
Fi Logo, possible trademark infringement

### ISSUE THREAD

**Issue by vothanhkiet** [ventuso/Fi-Test#72]
I noticed this morning, Fi logo and WebScaleSQL are too much alike, this can be a problem when we start the product.

![fi_logo_multi_black](https://cloud.githubusercontent.com/assets/4302582/7016979/537344e4-dd1a-11e4-8110-3a9d64139eca.png)
![webscalesql1](https://cloud.githubusercontent.com/assets/4302582/7016980/53740a3c-dd1a-11e4-913b-15d3950ce6c2.jpg)

**Comment by vothanhkiet** [comment]
@tomtheall

**Comment by tomtheall** [comment]
Thanks for the observation, haven't heard of WebScaleSQL. Some similarities but not close enough for concern. The companies are in different spaces and Fi's unique identity shouldn't be a problem.
