### ISSUE TITLE
iOS - rough transition between home and HereNow/Featured feed

### ISSUE THREAD

**Issue by tomtheall** [ventuso/Fi-Test#76]
On iOS, the transition between the home page (screenshot 1) and the HereNow/Featured feeds beneath (screenshot 2) needs to be smooth. These pages are currently snapping up or down unpredictably. 

I believe the Android version is working closer to the prototype (smooth sliding) so I assume there is a reason the iOS version is causing problems. Let me know more direction is needed.

Just wanted to document this as an issue that needs fixing. Thanks!

![img_4628](https://cloud.githubusercontent.com/assets/11476339/7076427/f2744b14-dece-11e4-8fe2-46e5a0387b5b.PNG)

![img_4629](https://cloud.githubusercontent.com/assets/11476339/7076429/f684643c-dece-11e4-9f88-25624dd6c027.PNG)

**Comment by baonguyenventuso** [comment]
@tomtheall 

Technically, the page on iOS different from Android due to each OS. 

On iOS, there are different in "events" that setting on the screen for animations. The similar one is used for sliding up and down from a Merchant view to Merchant detail, therefore, the require similar like Android could not be done.

**Comment by tomtheall** [comment]
Okay thanks. Let us know if can be figured out and if you are continuing to research it. If the interaction is absolutely impossible, something else will need to be a designed. 

I had some difficulty with this in the prototype as well. I have seen it done in other apps, let me know if you need references? Check out the google app, they have a similar home "swipe up and reveal" interaction for the main home interface.

Thanks!

**Comment by tomtheall** [comment]
Here also is another google app that does something similar. Google Maps.
Video Example: https://drive.google.com/file/d/0B7ky67jSyQ0NYXZSZ3FEUDczVjA/view?usp=sharing

Pretend the card that pulls up from the bottom is the page. Any ideas how they do this?
