### ISSUE TITLE
iOS - user is able to copy passwords and paste in visible text document

### ISSUE THREAD

**Issue by tomtheall** [ventuso/Fi-Test#77]
When connecting, network passwords should never be shown to users, the password exchange should all happen in the background, very secure, very private. Taren, is this correct?

For iOS, since Apple does not allow WiFi management...we discussed a workaround system where the user:

1. clicks "Connect" 
2. Shown a message instructing the user to go to WiFi settings, select the [network name], and paste the password.
3. User clicks "Show WiFi list"
4. Password is copied to clipboard and list of available networks is displayed.
5. If user selects ANYTHING BUT the network, the clipboard clears and the password is deleted. Selecting the corresponding network prompts the password, user then PASTES the password in the field and taps "Join". (password only displays as dots, the user shouldn't be able to paste it anywhere else)

SUCCESS!

Taren, Ken is this all correct? Is this possible?

Is there a special "copy" command that only allows paste into invisible fields and not visible documents? Could be another solution, PLEASE ADVISE.

**Comment by TarenJP** [comment]
Yes.   This needs addressed as outlined here by Tom.

Taren

**Comment by baonguyenventuso** [comment]
@tomtheall, @TarenJP 

Unfortunately, this is impossible to do that the moment. 
1. Can not navigate from the Fi app to Network List in device's Setting, only can come to device Setting but can not go further. 
2. Anything outside the app, like read a list of network around or check if user tap on ANYTHING BUT the network, is impossible to access. 

So, to simple this flow on iOS, we can understand that Apple does not allow App to control anything outside the app or control any other part of the device. 

We tried a lot of ways to solve this problem and I did a lot of research to find a possible solution to hide the password from user but seem there are no possible solution until now. 

Best regards,
T. Bao

**Comment by tomtheall** [comment]
Okay, Let's just send them to the root page of the settings app, at least that is one less action they have to do.

So...
1. When a network is available and in range, user taps "connect".
2. They get an alert that tells them what will happen next. For now let's say:
"Password Copied
Your device does not allow Fi to connect to this network automatically. In your WiFi settings, tap "[network_name]" and paste the password to connect."
— Cancel    — Go To Settings
3. Tapping "Go To Settings" takes user to the Settings app. From there they'll have to figure it out on their own, and then return back to the Fi app.

Taren, Ken, any other thoughts? Taren are you okay with letting iOS users see the password (if they really wanted to)?  In theory, if someone is on a network today they would have had to see the password...and open networks don't have any passwords at all, correct?

Later we may need to design a custom pop-up that visually illustrates a diagram of this process to make absolutely clear (Step 1, Step 2, Step 3,) This connection process is the most crucial part of the product, important to the app we'll need to test out different possibilities to find the best.
