### ISSUE TITLE
HereNow and Featured feeds need to be shown on network home (default state)

### ISSUE THREAD

**Issue by tomtheall** [ventuso/Fi-Test#78]
On the Network Home Page, News feed is currently displaying too low and off screen.
Please shift elements higher up on the page to allow the news feed show a little bit on the default state. 

Use the alignment comparison below as reference. I am mainly looking at iOS but I think this is an issue on Androids also.

![edits-13](https://cloud.githubusercontent.com/assets/11476339/7078108/eb2995a0-dedb-11e4-88a8-f652c47d37e8.jpg)

**Comment by baonguyenventuso** [comment]
I agree with this, it make the app nicer. Fix this issue also help to solve issue #76  which I already closed/won't fix by technical matter.

**Comment by dangtran89** [comment]
android fixed in 1.0.27
