### ISSUE TITLE
Change error alert when sending messages while not connected

### ISSUE THREAD

**Issue by tomtheall** [ventuso/Fi-Test#79]
The alert that shows when trying to send a message while not connected to a network needs to be reworded....

When user is in range:
"You must connect to network's WiFi to share messages."
- Connect
- Close

When user is not in range:
"Only users on this network's WiFi can broadcast."
- Get Directions
- OK

![](http://i.imgur.com/FADE6kD.jpg)

**Comment by nhanventuso** [comment]
iOS fix on version 1.0.38
