### ISSUE TITLE
VERIFY ACCOUNT screen has misspelled words

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#8]
Testing on Iphone 5.
Software version 8.1.3
FI version 1.0.10

"VERIFY ACCOUNT" screen to enter in the 4 digit verification code from a text message has 3 misspelled words on it.
See attached snapshot.
![img_0142](https://cloud.githubusercontent.com/assets/11478454/6658699/761a3ad0-cb3f-11e4-8694-18fdcdfba6b9.PNG)

**Comment by nhanventuso** [comment]
receive, verification, below
