### ISSUE TITLE
Android animations are broken in release 1.0.23

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#80]
Samsung Galaxy Note 2

After installing the latest release, the Merchant Home Pages behaved strange.

1) opened Fi
2) zoomed to dallas and tapped on the City Tavern pop-up
3) Strange behavior below occurred.  

![image](https://cloud.githubusercontent.com/assets/8836291/7102330/64272744-e042-11e4-98a5-b25322668585.png)

![image](https://cloud.githubusercontent.com/assets/8836291/7102337/8cbc43ce-e042-11e4-9fd6-a44da70f3aa4.png)

![image](https://cloud.githubusercontent.com/assets/8836291/7102339/a041b96a-e042-11e4-8946-72a6810ed21d.png)

**Comment by dangtran89** [comment]
android fix in 1.0.24
