### ISSUE TITLE
Connect and Follow buttons missing text in Android 5.0.1

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#82]
Device information:
Release: Fi for Android 1.0.23 
HW: Samsung Note 4
SW:  Android 5.0.1 Lollipop

![mapbutton_missingtext](https://cloud.githubusercontent.com/assets/8836291/7107277/50325cba-e126-11e4-98bb-d920327d41e6.jpg)
![button text missing_0](https://cloud.githubusercontent.com/assets/8836291/7107278/503535de-e126-11e4-8644-9c47221c7710.jpg)

**Comment by baonguyenventuso** [comment]
@TarenJP 

Thanks Taren, we are also meet this issue here since one of our device updated to 5.0. It happened due to new updated/ required of Android OS. This will be fixed in the next release. 

Best regards, 
T. Bao

**Comment by dangtran89** [comment]
android fix in 1.0.24
