### ISSUE TITLE
Exclusive offer text overlaps the Exclusive Offer Timer (clock symbol)

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#84]
![bonus timer overlaps text_0](https://cloud.githubusercontent.com/assets/8836291/7107504/c5beafdc-e12c-11e4-87c2-4e354927f181.jpg)

**Comment by baonguyenventuso** [comment]
@TarenJP 

First of all, we will move the Timer place to avoid the overlap. Please instruct or giving us kind of counting down timer, better on a designed page. I understand this and working with Service Team on it. 

Regards,
T. Bao

**Comment by dangtran89** [comment]
android fix in 1.0.24
