### ISSUE TITLE
Floating button blocks access to another Text Link 

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#85]
Most apps I've seen that have this floating button are putting them in the lower corners.  See Gmail Example.  

![floatingbutton_blocks_activelink](https://cloud.githubusercontent.com/assets/8836291/7107603/9a396aa2-e12f-11e4-84b4-8b4104c8506f.jpg)

<<--------- Gmail Example -------->>

![gmail_floater_example](https://cloud.githubusercontent.com/assets/8836291/7107608/b6465728-e12f-11e4-8813-c24c78acc554.jpg)

**Comment by nhanventuso** [comment]
iOS fix on version 1.0.37

**Comment by dangtran89** [comment]
android fix on 1.0.24
