### ISSUE TITLE
Fi app stucks in spinning wheel when tap on "Save To Gallery"

### ISSUE THREAD

**Issue by kenle99** [ventuso/Fi-Test#86]
I think the issue was the image got delete from FiRe portal.  So when I Tom tap on the "Save To Gallery", it keeps only spinning.  We should popup a warning to let user know that the image/photo has been deleted.  "Sorry. The image has been deleted by owner."
![img_4678](https://cloud.githubusercontent.com/assets/8815191/7128631/99eeada0-e21a-11e4-9ae3-f71fe6963e4f.PNG)

**Comment by baonguyenventuso** [comment]
@kenle99 

Yes, I assigned @thanhpq on this. It will be fixed soon.

Regards, 
T. bao

**Comment by nhanventuso** [comment]
iOS fix on version 1.0.39

**Comment by dangtran89** [comment]
android fixed in 1.0.27
