### ISSUE TITLE
Long text messages in MessageNow cover up other users texts

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#88]
IPhone 5C 8.2
Fi version 1.0.36
Connected to range.  
Went into MessageNow and typed in a long text message.
Left  and went back into MessageNow. 
The long text message covers up other people's messages.
See image below.
![img_0162](https://cloud.githubusercontent.com/assets/11478454/7128872/1cb4db80-e21e-11e4-8ead-51c4b782c6c5.PNG)

**Comment by baonguyenventuso** [comment]
@troywa 

We got this issue. It will be fixed in the next release.

Thanks & regards,
T. Bao

**Comment by nhanventuso** [comment]
iOS fix on version 1.0.39
