### ISSUE TITLE
Expiration dates on BONUS windows don't appear to be correct or line up

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#89]
IPhone 5C 8.2
Fi 1.0.36
Connected to Range
Click on Bonus applet
Bonus picture comes up and shows  16 days to the bottom right of the picture.
If you then click on the bonus picture it brings up another page that shows 12 min left at bottom right of window.
Then at the bottom of the page is shows Expires: 2hrs 33 mins
![img_0165](https://cloud.githubusercontent.com/assets/11478454/7129161/0f1a6644-e222-11e4-8455-b5569245ba93.PNG)
![img_0164](https://cloud.githubusercontent.com/assets/11478454/7129164/15495336-e222-11e4-8e06-4571f24fccac.PNG)

**Comment by baonguyenventuso** [comment]
@troywa 
We got this issue and can procedure from here. 

Thanks,
T.Bao

**Comment by nhanventuso** [comment]
iOS fixed on version 1.0.38
