### ISSUE TITLE
Received an Alert when I opened the FI app on phone when not connected to anyone

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#9]
Testing on Iphone 5.
Software version 8.1.3
FI version 1.0.10

Received the following alert when I was at the Range building but had not connected to range or anyone else yet.  Had not requested to sign up yet to FI.
When I touched the FI app to open it this alert popped up.
![img_0144](https://cloud.githubusercontent.com/assets/11478454/6658760/d09ad88c-cb41-11e4-8736-dae5af2915b5.PNG)

**Comment by jweid** [comment]
this occurred to me when I accessed Fi at Range for the first time tonight on a iPhone 5s

**Comment by baonguyenventuso** [comment]
@troywa @jweid 
This is strange while this message set for a Merchant in Vietnam as our main test Merchant. I will check this case, please help to notice us if you continue to see it on 1.0.15 version. 

Thanks & regards,

**Comment by nhanventuso** [comment]
I fixed.
