### ISSUE TITLE
Constantly getting Range Alert every few minutes while always connected to Range Network

### ISSUE THREAD

**Issue by troywa** [ventuso/Fi-Test#90]
IPhone 5C 8.2
Fi 1.0.36
Constantly receiving the Range alter while connected to Range's network.
Some of the alters come in groups of 3 at a time.
![img_0163](https://cloud.githubusercontent.com/assets/11478454/7129196/8fdb5eaa-e222-11e4-9c24-3a916a310dfd.PNG)

**Comment by baonguyenventuso** [comment]
@troywa 

This usually happen when your phone automatic drop off and re-connect to Range continuously. But let's we check on this. 

Regards,

**Comment by kenle99** [comment]
I think this is related to the way we implement the wake up and send Location Status to keep the app from being killed by iOS.  I noticed I never get disconnected from wifi.  But I still get the static ad popup.  So please check on this again.

**Comment by nhanventuso** [comment]
I don't see it on iOS version 1.0.47 , please help me to test again.
