### ISSUE TITLE
Received a strange "Destroyy" message after using the Android back button

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#92]
Fi icons were unresponsive. 
Clicked back button. 
"Back" was displayed. 
"Destroyy" was then displayed.

![destroyymessage](https://cloud.githubusercontent.com/assets/8836291/7172034/9d01e39e-e3a6-11e4-8c18-b94619a0ceab.jpg)

**Comment by dangtran89** [comment]
android fix in v1.0.24
