### ISSUE TITLE
Fi failed to connect at Fox and Hound (f8:d1:11:bc:70:c2)

### ISSUE THREAD

**Issue by TarenJP** [ventuso/Fi-Test#94]
Tapped connect button - Fi would never connect.  Looked like Fi never got to the point where it switches WiFi on.  Occurred around 21:11 CST.  

Similar occurrence at  John Weidenfeller's home network and again Taco Joint in Richardson earlier that evening.  However, my OS seemed to be trying desperately to connect to a nearby Open Network (HPBwifi), instead of the Taco Joint WiFi.  Both of these events occurred between 20:25 and 20:38 CST.  

I assume these issues are related so, I am opening a single Bug Report for them.  

![image](https://cloud.githubusercontent.com/assets/8836291/7172170/88d0ce1a-e3a8-11e4-813f-62517ba8dbee.png)

![image](https://cloud.githubusercontent.com/assets/8836291/7172196/f4228adc-e3a8-11e4-9b55-8eb9cd141723.png)

![image](https://cloud.githubusercontent.com/assets/8836291/7172199/0f275d62-e3a9-11e4-8a3c-516a5023dad6.png)

TACO JOINT CONNECTION FAILING but showing "Connected" snapshots............

![image](https://cloud.githubusercontent.com/assets/8836291/7172204/26b453c2-e3a9-11e4-9363-83ea8e803439.png)

![image](https://cloud.githubusercontent.com/assets/8836291/7172210/3b921716-e3a9-11e4-9a04-91fc0d92d904.png)

**Comment by dangtran89** [comment]
Here is Android step of connecting :
+ trying to connect to the target wifi
+ if success , the state going to change to connected , 
+ else after 10 second , autoconnect wifi will be triggered. Fi will automatically find a strongest Fi'signal wifi and connect to it
So in this case , please try to connect to Fox and Hound manually by wifi setting in the device. If it cannot connect to Fox and Hound then Fi App cannot do it either.
We are working on improve this issue .
Thanks
